version: '3'

networks:
    poker-moons:

volumes:
    redis_data:

services:
    redis:
        image: redis:alpine
        command: redis-server
        ports:
            - 6379:6379
        networks:
            - poker-moons
        volumes:
            - redis_data:/data
